spring.application.name=job-portal-backend
# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/job_portal

spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=8080

# ===============================
# JPA / HIBERNATE CONFIGURATION
# ===============================
# Hibernate DDL Auto (options: none, validate, update, create, create-drop)
spring.jpa.hibernate.ddl-auto=update

# Optional: show SQL in console
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

file.upload-dir=uploads

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=40MB

# JWT
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# 24 hours in milliseconds
jwt.expiration=86400000
# 7 days in milliseconds
jwt.refresh-expiration=604800000


# Security
security.allowed-origins=http://localhost:4200